export const ACTIVITY_LIST_REQUEST = 'ACTIVITY_LIST_REQUEST'
export const ACTIVITY_LIST_SUCCESS = 'ACTIVITY_LIST_SUCCESS'
export const ACTIVITY_LIST_FAIL = 'ACTIVITY_LIST_FAIL'

export const ACTIVITY_DETAILS_REQUEST = 'ACTIVITY_DETAILS_REQUEST'
export const ACTIVITY_DETAILS_SUCCESS = 'ACTIVITY_DETAILS_SUCCESS'
export const ACTIVITY_DETAILS_FAIL = 'ACTIVITY_DETAILS_FAIL'

export const ACTIVITY_DELETE_REQUEST = 'ACTIVITY_DELETE_REQUEST'
export const ACTIVITY_DELETE_SUCCESS = 'ACTIVITY_DELETE_SUCCESS'
export const ACTIVITY_DELETE_FAIL = 'ACTIVITY_DELETE_FAIL'