# Generated by Django 4.0.4 on 2022-06-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_activity_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='link',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='numPeople',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='numReviews',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='rating',
        ),
    ]
