# Generated by Django 4.0.4 on 2022-05-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_cost_activity_price_activity_numreviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='numPeople',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
