# Generated by Django 4.0.4 on 2022-06-22 09:50

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('base', '0006_activity_numpeople'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
