# Generated by Django 4.0.4 on 2022-06-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_activity_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, default='/chang-duong-Sj0iMtq_Z4w-unsplash.jpg', null=True, upload_to=''),
        ),
    ]
