const activities = [
  {
    '_id': '1',
    'location': '#01-07 College Ave West, Stephen Riady Centre, 138607',
    'cost': 10,
    'link': "",
    'description': 'Fried food where students typically eat for supper',
    'type': 'Supper',
    'genre': '',
    'purpose': 'Eat',
    'colour': 'Green',
  },
  {
    '_id': '2',
    'location': 'Mandai Rd Track 7',
    'cost': 0,
    'link': "",
    'description': 'A reservoir in central Singapore to exercise',
    'type': 'Catch the Sunset',
    'genre': 'Romantic',
    'purpose': 'Relax',
    'colour': 'Red',
  },
  {
    '_id': '3',
    'location': 'Palawan Beach',
    'cost': 20,
    'link': 'https://www.hydrodash.com.sg',
    'description': 'Get ready to climb, slide, leap and bounce your way through Hydrodash, Singapore\'s very first floating aqua park.',
    'type': 'Parkour',
    'genre': 'Sports',
    'purpose': 'Play',
    'colour': 'Blue',
  },
  {
    '_id': '4',
    'location': 'Universal Studios Singapore, Resorts World Sentosa',
    'cost': 80,
    'link': 'https://www.halloweenhorrornights.com.sg',
    'description': 'See amazing displays and installations showcasing the history of the iconic Halloween Horror Nights event.',
    'type': 'Showcase',
    'genre': 'Horror',
    'purpose': 'Play',
    'colour': 'Black',
  },
  {
    '_id': '5',
    'location': '6 Bayfront Ave, Singapore 018974',
    'cost': 14,
    'link': 'https://www.marinabaysands.com',
    'description': 'Future World: Where Art Meets Science',
    'type': 'Showcase',
    'genre': 'Documentary',
    'purpose': 'Play',
    'colour': 'Blue',
  },
  {
    '_id': '6',
    'location': '50 Jurong Gateway Rd, Singapore 608549',
    'cost': 0,
    'link': 'https://www.jem.sg',
    'description': 'Walk around a 3-storey mall full of food and clothgin.',
    'type': 'Shopping',
    'genre': 'Children & Family',
    'purpose': 'Relax',
    'colour': 'Green',
  },
]


export default activities
